server:
  port: 9292
spring:
  application:
    name:  Config Server 
  cloud:
    config:
      server:
        git:
          uri: https://github.com/adnanghori/Config-Server-Shopping-Cart
          username: # Enter Github Username
          password: # Enter Github token
          clone-on-start: true
eureka:
  instance:
    prefer-ip-address: true
  client:  
    register-with-eureka: true 
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka} 