server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb
    username: root
    password: Macbookair03
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format-sql: true
  application:
    name: Product-Service
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:  
#    register-with-eureka: true 
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
  config:
    import: configserver:http://localhost:9292