server:
  port: 8083
  
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/paymentdb
    username: root
    password: Macbookair03
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format-sql: true
  application:
    name: Payment-Service

  config:
    import: configserver:http://localhost:9292